blank_issues_enabled: false
contact_links:
  - name: Documentación de SPHERE
    url: https://sphere-docs.vercel.app/
    about: Antes de enviarnos tu pregunta, te animamos a echar un vistazo a la documentación –es posible que la respuesta ya esté ahí.
